name: voc

services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  db:
    image: mysql
    restart: always
    command: --log_error_verbosity=1  # errors only
    ports:
      - "13306:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env_prod
#    pre_stop:
#      - command: mysqldump -uroot -p$$MYSQL_PASSWORD $$MYSQL_DATABASE > vocab.sql
  web:
    image: web_app:3.6
    build:
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "db:3306", "--",
              "uwsgi", "--ini", "/app/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=vocbuilder.settings.prod
    depends_on:
      - db
  findjob:
    image: job_app:2.0
    build:
      context: ../findjob
    command: ["./wait-for-it.sh", "db:3306", "--",
              "uwsgi", "--ini", "/findjob_app/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - ../findjob:/findjob_app
    environment:
      - DJANGO_SETTINGS_MODULE=findjob.settings
    depends_on:
      - db
  nginx:
    image: nginx_local
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - .:/app
      - ../findjob:/findjob_app
    ports:
      - "80:80"
      - "443:443"
