# Generated by Django 5.0.4 on 2024-05-06 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language_from', models.CharField(max_length=2)),
                ('language_to', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.authors')),
            ],
        ),
        migrations.CreateModel(
            name='DictRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciation', models.CharField(max_length=200, null=True)),
                ('did_you_know_header', models.CharField(max_length=100, null=True)),
                ('did_you_know', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Derived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('pronunciation', models.CharField(max_length=200, null=True)),
                ('part_of_speech', models.CharField(max_length=100, null=True)),
                ('dict_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.dictrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(max_length=100)),
                ('dict_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.dictrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Etymology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(max_length=100)),
                ('etymology', models.TextField()),
                ('dict_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.dictrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dict_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.dictrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SenseSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.definition')),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('example', models.CharField(max_length=200, null=True)),
                ('labels', models.CharField(max_length=200, null=True)),
                ('usage_notes', models.CharField(max_length=200, null=True)),
                ('sense_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.sensesequence')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_word', models.CharField(max_length=200)),
                ('usage', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.word')),
            ],
        ),
    ]
