# Generated by Django 5.0.4 on 2024-05-06 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_dictrecord_url_inflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictrecord',
            name='word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vocab.word'),
            preserve_default=False,
        ),
    ]
