# Generated by Django 5.0.4 on 2024-05-06 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_rename_books_book_usage_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.book'),
        ),
    ]
