# Generated by Django 5.0.4 on 2024-05-06 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0006_alter_usage_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name_plural': 'dictionaries'},
        ),
        migrations.RemoveField(
            model_name='sense',
            name='example',
        ),
        migrations.RemoveField(
            model_name='sense',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='sense',
            name='usage_notes',
        ),
        migrations.CreateModel(
            name='SenseExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.sense')),
            ],
        ),
        migrations.CreateModel(
            name='SenseLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.sense')),
            ],
        ),
        migrations.CreateModel(
            name='SenseUsageNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_note', models.CharField(max_length=200)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.sense')),
            ],
        ),
    ]
