# Generated by Django 5.0.4 on 2024-05-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0008_alter_word_stem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictrecord',
            name='error_fetching',
            field=models.BooleanField(default=False),
        ),
    ]
