# Generated by Django 5.0.4 on 2024-05-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_dictrecord_error_fetching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etymology',
            name='part_of_speech',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
