# Generated by Django 5.0.4 on 2024-05-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0010_alter_etymology_part_of_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
