# Generated by Django 5.0.4 on 2024-05-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0011_alter_definition_part_of_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='sense',
            name='letter',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
