# Generated by Django 5.0.4 on 2024-05-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0012_sense_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField()),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.word')),
            ],
        ),
    ]
