# Generated by Django 5.0.4 on 2024-05-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0013_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='word_id',
            new_name='word',
        ),
    ]
