# Generated by Django 5.0.4 on 2024-05-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0016_feedback_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
